# Generated by Django 2.2.5 on 2019-11-24 22:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='OnlineShopperTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Administrative', models.IntegerField(default=0)),
                ('Administrative_Duration', models.FloatField(default=0)),
                ('Informational', models.IntegerField(default=0)),
                ('Informational_Duration', models.FloatField(default=0)),
                ('ProductRelated', models.FloatField(default=0)),
                ('ProductRelated_Duration', models.FloatField(default=0)),
                ('BounceRates', models.FloatField(default=0)),
                ('ExitRates', models.FloatField(default=0)),
                ('PageValues', models.FloatField(default=0)),
                ('SpecialDay', models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)])),
                ('Month', models.CharField(max_length=15)),
                ('OperatingSystems', models.IntegerField(validators=[django.core.validators.MaxValueValidator(0), django.core.validators.MinValueValidator(8)])),
                ('Browser', models.IntegerField(validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(13)])),
                ('Region', models.IntegerField(validators=[django.core.validators.MaxValueValidator(0), django.core.validators.MinValueValidator(9)])),
                ('TrafficType', models.IntegerField(validators=[django.core.validators.MaxValueValidator(0), django.core.validators.MinValueValidator(20)])),
                ('Visitor_type', models.CharField(choices=[('Returning', 'Returning_Visitor'), ('New', 'New_Visitor'), ('Other', 'Other')], max_length=50)),
                ('Weekend', models.CharField(choices=[('False', 'FALSE'), ('True', 'TRUE')], max_length=50)),
                ('Revenue', models.CharField(choices=[('False', 'FALSE'), ('True', 'TRUE')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('content', models.TextField(blank=True)),
                ('created', models.DateField(default='2019-11-24')),
                ('due_date', models.DateField(default='2019-11-24')),
                ('category', models.ForeignKey(default='general', on_delete=django.db.models.deletion.PROTECT, to='ErpDev.Category')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=150)),
                ('bio', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
