# Generated by Django 2.2.5 on 2019-11-16 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ErpDev', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlineshoppertable',
            name='Revenue',
            field=models.CharField(choices=[('False', 'FALSE'), ('True', 'TRUE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='onlineshoppertable',
            name='Weekend',
            field=models.CharField(choices=[('False', 'FALSE'), ('True', 'TRUE')], max_length=50),
        ),
    ]
