# Generated by Django 2.2.5 on 2019-11-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ErpDev', '0002_auto_20191124_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listtodo',
            name='created',
            field=models.DateField(default='2019-11-26'),
        ),
        migrations.AlterField(
            model_name='listtodo',
            name='due_date',
            field=models.DateField(default='2019-11-26'),
        ),
    ]
