# Generated by Django 2.2.5 on 2019-11-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ErpDev', '0002_auto_20191116_0633'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('content', models.TextField(blank=True)),
                ('created', models.DateField(default='2019-11-20')),
                ('due_date', models.DateField(default='2019-11-20')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
