# Generated by Django 2.2.5 on 2019-11-28 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ErpDev', '0004_auto_20191128_0546'),
    ]

    operations = [
        migrations.AddField(
            model_name='listtodo',
            name='username',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
